spring:
  application:
    name: stock-processor
  kafka:
    bootstrap-servers: macdaddy.local:29093
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    client:
      certificate:
hobbyinvestor:
  consumer:
    mongo-group-id: 987654321
    elasticsearch-group-id: 123456789
  topic-names:
    companyProfileUpdateTopic: companyProfileUpdate
    companyFinancialsUpdateTopic: companyFinancialsUpdate
    companyNewsUpdateTopic: companyNewsUpdate
  mongo:
    database-name: hobbyInvestor
    company-profile:
      uri: mongodb://macdaddy.local:27017/hobbyInvestor
  elastic-search:
    cluster-node: macdaddy.local:9200

